---

# Do VM boostrapping 
- include: common.yml

# Install and configure the database
- include: db.yml

- hosts: askbot
  name: install askbot webapp
  remote_user: root

  vars:
    proxy_env:
      http_proxy: "{{ proxy_host }}:{{ proxy_port }}"
      https_proxy: "{{ proxy_host }}:{{ proxy_port }}"

  tasks:
  - name: install virtualenv
    yum: name=python-virtualenv

  - name: install gcc, required for askbot dependencies
    yum: name=gcc
  - name: install psycopg2 into askbot virtualenv
    pip: name=psycopg2 virtualenv=/var/www/askbot
    environment: proxy_env

  # For some reason this dependency needs to be installed first
  - name: install askbot prerequisite setuptools-hg into virtualenv
    pip: name=setuptools-hg  virtualenv=/var/www/askbot
    environment: proxy_env

  - name: install askbot into virtualenv
    pip: name=askbot virtualenv=/var/www/askbot
    environment: proxy_env

  - name: run askbot-setup to create the webapp
    command: /var/www/askbot/bin/askbot-setup --db-engine=1 --db-name={{dbname}} --db-password={{dbpassword}} --db-user={{dbuser}} --dir-name=/var/www/askbot/app creates=/var/www/askbot/app/settings.py

  #!NOTE: The colon-character variable substitution is needed to work round a bug in the parser
  - name: patch settings.py to use a network socket for DB
    lineinfile: dest=/var/www/askbot/app/settings.py
      regexp="^(\s+)'HOST'{{':'}} '',(.*)" 
      line="\1'HOST'{{':'}} 'localhost',\2"
      backrefs=yes
      state=present

  - name: syncdb askbot
    command: /var/www/askbot/bin/python manage.py syncdb --noinput
      chdir=/var/www/askbot/app
  - name: migrate askbot
    shell: /var/www/askbot/bin/python manage.py migrate --noinput || true
      chdir=/var/www/askbot/app
