#
# 
#

- hosts: askbot
  name: Deploy askbot and all dependencies into a single host
  user: root
  roles:
    - jasmin
    - postgres
    - apache
    - memcached
    - askbot
  vars:
    - debug_email: yes
    - http_proxy: "{{ proxy_host }}:{{ proxy_port }}"
    - https_proxy: "{{ proxy_host }}:{{ proxy_port }}"
