#
# 
#

- hosts: askbot
  name: Deploy askbot and all dependencies into a single host
  user: root
  roles:
    - jasmin
    - postgres
    - apache
    - memcached
    - { role: askbot, app_name: askbot_esgf, app_vhost: askbot.localhost }
    - { role: askbot, app_name: askbot_clim4i, app_vhost: clim4i.localhost }
  vars:
    - debug_email: yes
    - http_proxy: "{{ proxy_host }}:{{ proxy_port }}"
    - https_proxy: "{{ proxy_host }}:{{ proxy_port }}"
