#
# An Ansible playbook for a self-contained Askbot installation
#

- hosts: askbot
  name: Deploy askbot and all dependencies into a single host
  user: root
  roles:
    # Include the jasmin role only if you are deploying on JASMIN.
    # jasmin

    # These roles install services Askbot depends on.
    - postgres
    - apache
    - memcached

    # List each Askbot instance here with their vhost.  Database passwords are automatically
    # saved to the ./lookups directory on the Ansible control host.
    #!WARNING: multiple instances don't work yet!
    - { role: askbot, app_name: askbot_uvcdat, app_vhost: askbot-uvcdat.llnl.gov,
          app_email: nospam@llnl.gov }
  vars:
    # If debug_email is yes then Askbot will not send out email but will save emails to a
    # directory instead (/var/www/askbot/<app_name>_site/log/messages)
    - debug_email: no
    # Required if you are behing the STFC proxy.
    - http_proxy: "{{ proxy_host }}:{{ proxy_port }}"
    - https_proxy: "{{ proxy_host }}:{{ proxy_port }}"
