---
- hosts: all
  name: ensure askbot user and database are created
  remote_user: root
  sudo: yes
  sudo_user: postgres
  gather_facts: no

  tasks:
  - name: ensure user does not have unnecessary privilege
    postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB

  - name: ensure database is created
    postgresql_db: name={{dbname}} owner={{dbuser}}

  - name: ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

  - name: Ensure posgres is listening on all localhost
    lineinfile: dest=/var/lib/pgsql/data/postgresql.conf
      regexp='^#?listen_addresses\s*='
      line="listen_addresses = '127.0.0.1'"
      state=present

  - name: Ensure md5 authentication for postgres
    lineinfile: dest=/var/lib/pgsql/data/pg_hba.conf
      regexp='host\s+all\s+all\s+127.0.0.1/32'
      line='host all all 127.0.0.1/32 md5'
      state=present

#!NOTE: not as user postgres
- hosts: all
  remote_user: root
  tasks:
  - name: restart postgresql
    service: name=postgresql state=restarted
